project:
  type: website
  output-dir: docs

website:
  title: "Social Media Analytics and Research"
  sidebar:
    #logo: "image/avatar.jpg"
    style: "docked"
    search: true
    contents:
      - text: "Home"
        file: index.qmd
      - text: "Schedule"
        file: schedule.qmd
      - section: "Tutorials" 
        contents: 
         - week3.qmd
         - week4.qmd
         - week5.qmd
         - week6.qmd
         - week8.qmd
         - week9.qmd
         - week10.qmd
         - week11.qmd
      - section: "Practices" 
        contents:
         
        

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual

