---
title: "Course schedule"
tbl-colwidths: [25,50]
---

+-----------------+------------------------------------------------------------------------------------+
| ### Weeks       | ### Topics                                                                         |
+:===============:+:==================================================================================:+
| Week 1: Aug 28  | Class overview and set-up                                                          |
+-----------------+------------------------------------------------------------------------------------+
| Week 2: Sep 4   | Labor Day - No Classes 😃                                                          |
+-----------------+------------------------------------------------------------------------------------+
| Week 3: Sep 11  | Overview of social media research\                                                 |
|                 | Lab: Get familiar with R/R Studio and data wrangling                               |
+-----------------+------------------------------------------------------------------------------------+
| Week 4: Sep 18  | What (social media) data is out there?\                                            |
|                 | Lab: Data collection -- API                                                        |
+-----------------+------------------------------------------------------------------------------------+
| Week 5: Sep 25  | How to utilize social media data?\                                                 |
|                 | Lab: Data collection -- Web scraping\                                              |
|                 | Final project idea due Oct 1                                                       |
+-----------------+------------------------------------------------------------------------------------+
| Week 6: Oct 2   | The pitfall of social media data\                                                  |
|                 | Lab: Data visualization                                                            |
+-----------------+------------------------------------------------------------------------------------+
| Week 7: Oct 9   | Fall break - No Classes 😃\                                                        |
|                 | [Practice 1 due on Oct 15]{style="color:orange;"}                                  |
+-----------------+------------------------------------------------------------------------------------+
| Week 8: Oct 16  | Case study: Text-as-data I\                                                        |
|                 | Lab: Basic text analysis                                                           |
+-----------------+------------------------------------------------------------------------------------+
| Week 9: Oct 23  | Case study: Text-as-data II\                                                       |
|                 | Lab: Topic modeling                                                                |
+-----------------+------------------------------------------------------------------------------------+
| Week 10: Oct 30 | Case study: Text-as-data III\                                                      |
|                 | Lab: Sentiment analysis\                                                           |
+-----------------+------------------------------------------------------------------------------------+
| Week 11: Nov 6  | Case study: Network\                                                               |
|                 | Lab: Network analysis                                                              |
+-----------------+------------------------------------------------------------------------------------+
| Week 12: Nov 13 | Course wrap-up and more (Q&A)\                                                     |
+-----------------+------------------------------------------------------------------------------------+
| Week 13: Nov 20 | Individual meetings & consultant [Practice 2 due on Nov 26]{style="color:orange;"} |
+-----------------+------------------------------------------------------------------------------------+
| Week 14: Nov 27 | Individual meetings & consultant                                                   |
+-----------------+------------------------------------------------------------------------------------+
| Week 15: Dec 4  | Project presentation                                                               |
+-----------------+------------------------------------------------------------------------------------+
| Week 16: Dec 15 | Final paper due                                                                    |
+-----------------+------------------------------------------------------------------------------------+
